// PHOTO GAMBAR

import alicia from '../assets/alicia.jpg?format=webp'
import achel from '../assets/achel.jpg?format=webp'
import leo from '../assets/leo.jpg?format=webp'
import farrel from '../assets/farrel.jpg?format=webp'
import geo from '../assets/geo.jpg?format=webp'
import fadhilla from '../assets/dilla.jpg?format=webp'
import cici from '../assets/cici.jpg?format=webp'
import gabriella from '../assets/gabriella.jpg?format=webp'
import iya from '../assets/iya.jpg?format=webp'
import billy from '../assets/billy.jpg?format=webp'
import idax from '../assets/evandrix.jpg?format=webp'
import supriadi from '../assets/supriadi.jpg?format=webp'
import sean from '../assets/sean.jpg?format=webp'
import januard from '../assets/januard.jpg?format=webp'
import niken from '../assets/niken.jpg?format=webp'
import indriani from '../assets/indriani.jpg?format=webp'
import delon from '../assets/delon.jpg?format=webp'
import mega from '../assets/mega.jpg?format=webp'
import andika from '../assets/andika.jpg?format=webp'
import amel from '../assets/amel.jpg?format=webp'
import muzamil from '../assets/muzamil.jpg?format=webp'
import reisky from '../assets/reisky.jpg?format=webp'
import valen from '../assets/valen.jpg?format=webp'
import christy from '../assets/christy.jpg?format=webp'
import aisyah from '../assets/aisyah.jpg?format=webp'
import julieo from '../assets/julieo.jpg?format=webp'
import faujia from '../assets/faujia.jpg?format=webp'
import stifangki from '../assets/stifangki.jpg?format=webp'
import jenifer from '../assets/jenifer.jpg?format=webp'
import stevani from '../assets/stevani.jpg?format=webp'
import marentek from '../assets/marentek.jpg?format=webp'
import tirsa from '../assets/tirsa.jpg?format=webp'
import debora from '../assets/debora.jpg?format=webp'

// LAMPIRAN

// Sean
import seanLampiran1 from '../assets/lampiran/sean/Picture1.png?format=jpg'
import seanLampiran2 from '../assets/lampiran/sean/Picture2.png?format=jpg'







const DataMahasiswa = [
    {
        Photo: amel,
        Nama: 'Amels Wisye Margareth Sasauw',
        NIM: '2205002',
        Angkatan: '2022',
        judul: 'Sistem Informasi Inventarisasi Aset Daerah Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: alicia,
        Nama: 'Alicia Aurelia Hebingadil',
        NIM: '2205003',
        Angkatan: '2022',
        judul: 'Pengembangan Web GIS Sistem Pemantauan Hasil Perikanan',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Junior Kefas Mahino',
        NIM: '2205004',
        Angkatan: '2022',
        judul: 'Sistem Informasi Sebaran Anak Stunting di Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Mersita Trisce Letunggamu',
        NIM: '2205006',
        Angkatan: '2022',
        judul: 'Sistem Informasi Akreditasi Sekolah di Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: reisky,
        Nama: 'Reisky Mendalora Sahentumuwo',
        NIM: '2205009',
        Angkatan: '2022',
        judul: 'Web GIS Sebaran Lahan Pertanian di Tahuna Barat',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: cici,
        Nama: 'Regina Glorita Makaluase',
        NIM: '2205010',
        Angkatan: '2022',
        judul: 'Sistem Informasi Penyediaan Air Moil Tangki Berbasis Website',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: fadhilla,
        Nama: 'Fadhilla Wahyuni Soleman',
        NIM: '2205011',
        Angkatan: '2022',
        judul: 'Analisis Sistem Monitoring Infrastruktur pada Program Pembangunan dan Pemberdayaan Masyarakat dan Desa',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: januard,
        Nama: 'Januard Reynaldi Alexandro Andaria',
        NIM: '2205013',
        Angkatan: '2022',
        judul: 'Sistem Informasi Event dan Reservasi Makanan di KOPITIAM Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: valen,
        Nama: 'Greyfer Valentino Papendang Legrants',
        NIM: '2205014',
        Angkatan: '2022',
        judul: 'Sistem Informasi Monitoring Harga Sembako Berbasis Web pada Dinas Perindustrian dan Perdagangan Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: mega,
        Nama: 'Mega Olivia Busia Pinta',
        NIM: '2205015',
        Angkatan: '2022',
        judul: 'Sistem Infromasi Kesehatan Posyandu Anak Balita Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Akhsa Angel Tumbale',
        NIM: '2205016',
        Angkatan: '2022',
        judul: 'Membuat Surat Keterangan Kehilangan Barang Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: christy,
        Nama: 'Christy Stevani Tamusa',
        NIM: '2205017',
        Angkatan: '2022',
        judul: 'Sistem Infromasi Kesehatan Gizi Remaja Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: aisyah,
        Nama: 'Sitti Aisyah Mahare',
        NIM: '2205019',
        Angkatan: '2022',
        judul: 'Pengembangan Sistem Monitoring Infrastruktur Pada Program Pembangunan dan Pemberdayaan Masyarakat',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: idax,
        Nama: 'Evandrix Mamintade',
        NIM: '2205020',
        Angkatan: '2022',
        judul: 'Digitalisasi Potensi Kampung Kawio Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: achel,
        Nama: 'Firstonly Marshel Naharia',
        NIM: '2205021',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: andika,
        Nama: 'Andika Eka Koming',
        NIM: '2205023',
        Angkatan: '2022',
        judul: 'Aplikasi Pengolahan Data Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Jessica Juanita Lombontari',
        NIM: '2205024',
        Angkatan: '2022',
        judul: 'Inventaris SOP pada Lembaga Pemasyarakatan Kelas III Enemawira Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: faujia,
        Nama: 'Faujia Kondoalumang',
        NIM: '2205025',
        Angkatan: '2022',
        judul: 'Sistem Informasi Layanan Pendaftaran Penyambungan Baru di PDAM Berbasis Website',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: iya,
        Nama: 'Zuwairyah Kantohe',
        NIM: '2205026',
        Angkatan: '2022',
        judul: 'Sistem Informasi Pendaftaran dan Pendampingan UMKM di Loka POM Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Sheren Zyallomitha Zhakilla Makawimbang',
        NIM: '2205030',
        Angkatan: '2022',
        judul: 'Desain UI/UX Inventaris SOP pada Lembaga Pemasyarakatan Kelas III Enemawira',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: julieo,
        Nama: 'Julieo Yusuf Kagingge',
        NIM: '2205031',
        Angkatan: '2022',
        judul: 'Sistem Informasi Manajemen (SIM) Data Perpustakaan',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: supriadi,
        Nama: 'Supriadinata Masihor',
        NIM: '2205032',
        Angkatan: '2022',
        judul: 'Sistem Informasi Penjualan Produk UMKM Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: stifangki,
        Nama: 'Stifangki Josua Rivan Kakunsi',
        NIM: '2205033',
        judul: 'Pemanfaatan Aplikasi ArcGIS untuk Jalur Evakuasi Gunung Berapi Awu',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Muhammad Syahban Tempongbuka',
        NIM: '2205034',
        judul: 'Sistem Informasi Jalur Pipa PDAM Berbasis Web GIS',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: delon,
        Nama: 'Novaldi Delon Takalalumang',
        NIM: '2205038',
        Angkatan: '2022',
        judul: 'Optimalisasi Aplikasi Berperforma Tinggi dengan Redis pada VPS Ubuntu',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: jenifer,
        Nama: 'Jenifer Sartika Lalenoh',
        NIM: '2205039',
        Angkatan: '2022',
        judul: 'Sistem Informasi Manajemen Proyek Konstruksi Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Revalin Terah Wolff',
        NIM: '2205040',
        Angkatan: '2022',
        judul: 'Sistem Informasi Layanan Masyarakat pada POLSEK Tahuna Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: stevani,
        Nama: 'Stevani Patiri',
        NIM: '2205041',
        Angkatan: '2022',
        judul: 'Penggunaan Drone untuk Identifikasi Pergeseran Garis Pantai (Studi Kasus: Kecamatan Tabukan Utara)',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: geo,
        Nama: 'Geovani Marchiano Monok',
        NIM: '2205042',
        Angkatan: '2022',
        judul: 'Website Monitoring Aktivitas Kunjungan Kawasan Gunung Sahendarumang',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: muzamil,
        Nama: 'Muzamil Paputungan',
        NIM: '2205043',
        Angkatan: '2022',
        judul: 'Pengelolaan Data Sebaran Keragaman Hayati Hutan Lindung Sahendarumang 2 Berbasis Web Gis',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Reggi Saputra Salawangi',
        NIM: '2205044',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Salsabillah Kaehe',
        NIM: '2205047',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Fryska Armelia Towoliu',
        NIM: '2205048',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: tirsa,
        Nama: 'Tirsa Olivia Talete',
        NIM: '2205049',
        Angkatan: '2022',
        judul: 'Desain UI/UX Sistem Informasi Ecent dan Reservasi Makanan di KOPITIAM Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: niken,
        Nama: 'Aniken Amasya Lendeon',
        NIM: '2205050',
        Angkatan: '2022',
        judul: 'Sistem Informasi Penilaian Kualitas Layanan Wisata Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: debora,
        Nama: 'Regina Debora Lahamendu',
        NIM: '2205051',
        Angkatan: '2022',
        judul: 'Web GIS Sebaran Lahan Pertanian di Tahuna Barat',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: marentek,
        Nama: 'Marchel Hezzel Marentek',
        judul: 'Penyewaan Lapangan Futsal Berbasis Web',
        NIM: '2205052',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: indriani,
        Nama: 'Indriani Gratsia Tumimbang',
        NIM: '2205054',
        Angkatan: '2022',
        judul: 'Desain UI/UX Sistem Informasi Manajemen Proyek Konstruksi',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Yohana Tompo',
        NIM: '2205055',
        Angkatan: '2022',
        judul: 'Rancang Bangun Sistem Informasi Promosi Destinasi Wisata pada Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: gabriella,
        Nama: 'Gabriella Kristania Citra Kakomole',
        NIM: '2205057',
        Angkatan: '2022',
        judul: 'Desain UI/UX Pendaftaran dan Pendampingan UMKM di Loka POM Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: billy,
        Nama: 'Billy Amstrong Tempolenehe',
        NIM: '2205059',
        Angkatan: '2022',
        judul: 'Sistem Informasi Statistik Usaha Mikro Kecil Menengah Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Tasya Lawitang',
        NIM: '2205060',
        Angkatan: '2022',
        judul: 'Web GIS Laporan Operasi SAR',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Vanessa Tesalonika Dhea Bundel',
        NIM: '2205061',
        Angkatan: '2022',
        judul: 'Rekomendasi Usaha Pariwisata Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: farrel,
        Nama: 'Farrel Patrick Kaburuang',
        NIM: '2205062',
        Angkatan: '2022',
        judul: 'Sistem Informasi Profil Dinas Sosial Daerah Kabupaten Kepulauan Sangihe Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Sela Ester Laodini',
        NIM: '2205063',
        Angkatan: '2022',
        judul: 'Pengembangan Sistem Pelaporan Orang Hilang Berbasis Mobile',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: leo,
        Nama: 'Leo Richardo Alelo',
        NIM: '2205064',
        Angkatan: '2022',
        judul: 'Pengembangan Backend Website Attendance Management System',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: sean,
        Nama: 'Sean Ishak Adare',
        NIM: '2205066',
        Angkatan: '2022',
        judul: 'Pengembangan Frontend Website Attendance Management System Berbasis ReactJS & TailwindCSS',
        abstrak: 'Attendance Management System (AMS) merupakan sebuah aplikasi berbasis web yang dirancang untuk mempermudah pengelolaan data kehadiran secara efisien dan terintegrasi. Sistem ini bertujuan untuk menggantikan metode manual yang rentan terhadap kesalahan pencatatan dan membutuhkan waktu lama dengan solusi digital yang lebih akurat dan mudah digunakan. AMS memungkinkan pengguna, baik administrator maupun pengguna akhir, untuk mencatat, memantau, dan mengelola kehadiran secara real - time melalui antarmuka yang intuitif. Pengembangan AMS menggunakan teknologi ReactJS, Vite, TailwindCSS untuk antarmuka pengguna, serta ExpressJS pada sisi backend, memastikan performa yang cepat dan responsif. Sistem ini mendukung berbagai fitur seperti pencatatan kehadiran berbasis waktu nyata, pengelolaan data pengguna, laporan kehadiran yang dapat diunduh, dan pengaturan izin pengguna. Dengan implementasi AMS, institusi pendidikan, perusahaan, maupun organisasi lainnya dapat meningkatkan efisiensi pengelolaan kehadiran, mengurangi risiko kesalahan data, serta mempermudah analisis kehadiran melalui laporan yang komprehensif. Sistem ini memberikan solusi yang relevan untuk kebutuhan manajemen kehadiran modern.',
        journalLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        lampiran: seanLampiran1,
        lampiran1: seanLampiran2,
        lampiran2: 'https://via.placeholder.com/150',
    },
]

export default DataMahasiswa