// PHOTO GAMBAR 2022

import alicia from '../assets/alicia.jpg?format=webp'
import achel from '../assets/achel.jpg?format=webp'
import leo from '../assets/leo.jpg?format=webp'
import farrel from '../assets/farrel.jpg?format=webp'
import geo from '../assets/geo.jpg?format=webp'
import fadhilla from '../assets/dilla.jpg?format=webp'
import cici from '../assets/cici.jpg?format=webp'
import gabriella from '../assets/gabriella.jpg?format=webp'
import iya from '../assets/iya.jpg?format=webp'
import billy from '../assets/billy.jpg?format=webp'
import idax from '../assets/evandrix.jpg?format=webp'
import supriadi from '../assets/supriadi.jpg?format=webp'
import sean from '../assets/sean.jpg?format=webp'
import januard from '../assets/januard.jpg?format=webp'
import niken from '../assets/niken.jpg?format=webp'
import indriani from '../assets/indriani.jpg?format=webp'
import delon from '../assets/delon.jpg?format=webp'
import mega from '../assets/mega.jpg?format=webp'
import andika from '../assets/andika.jpg?format=webp'
import amel from '../assets/amel.jpg?format=webp'
import muzamil from '../assets/muzamil.jpg?format=webp'
import reisky from '../assets/reisky.jpg?format=webp'
import valen from '../assets/valen.jpg?format=webp'
import christy from '../assets/christy.jpg?format=webp'
import aisyah from '../assets/aisyah.jpg?format=webp'
import julieo from '../assets/julieo.jpg?format=webp'
import faujia from '../assets/faujia.jpg?format=webp'
import stifangki from '../assets/stifangki.jpg?format=webp'
import jenifer from '../assets/jenifer.jpg?format=webp'
import stevani from '../assets/stevani.jpg?format=webp'
import marentek from '../assets/marentek.jpg?format=webp'
import tirsa from '../assets/tirsa.jpg?format=webp'
import debora from '../assets/debora.jpg?format=webp'

// LAMPIRAN

// Sean
import seanLampiran1 from '../assets/lampiran/sean/Picture1.png?format=jpg'
import seanLampiran2 from '../assets/lampiran/sean/Picture2.png?format=jpg'

// PHOTO GAMBAR 2021
import alesandro from '../assets/2021/alesandro.png?format=webp'
import alexandro from '../assets/2021/alexandro.png?format=webp'


const DataAngkatan = [
    {
        Angkatan: '2021',
    },
    {
        Angkatan: '2022',
    },
    {
        Angkatan: '2023',
    },
    {
        Angkatan: '2024',
    },
]

export { DataAngkatan }

const DataMahasiswa2021 = [
    {
        Photo: alesandro,
        Nama: 'Alessandro Danielo Pangandaheng',
        NIM: '2105003',
        Angkatan: '2021',
        judul: 'Sistem Monitoring Kelistrikan Billboard LED Videotron Berbasis IoT',
        abstrak: 'Kebutuhan akan Listrik pada kehidupan sehari-hari sangatlah penting bagi para masyarakat. Sakaeng Solata adalah bagian instansi yang bergerak sebagai penyedia jasa internet dan multimedia, pada penelitian ini dibuatlah sistem pemantauan kelistrikan pada sebuah billboard atau yang biasanya disebut papan iklan, yang berteknologi videotron. Dashboard pada sistem pemantauan tersebut dibuat berbasis web agar lebih memudahkan pengguna untuk melakukan pemantauan pada sistem kelistrikan tersebut. Pemantauan kelistrikan ini diperlukan agar pengguna bisa memantau sekian banyak total penggunaan Daya, kWh, Arus, Tegangan Listrik dan juga memberi peringatan ketika melibihi beban arus agar terhindar dari kebakaran. Pemanfaatan Teknologi IoT dengan baik dapat membantu pengguna bisa mendapatkan informasi melallui website tersebut. Maka dibutuhkannya sebuah Sistem Monitoring Kelistrikan Billboard LED Videotron Berbasis IoT.',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: alexandro,
        Nama: 'Alexandro Savior Manihing',
        NIM: '2105004',
        Angkatan: '2021',
        judul: 'Penerapan Geographic Information System Open Source Data Geospasial Kependudukan Kampung Pinebentengang',
        abstrak: 'Penelitian ini bertujuan untuk mengumpulkan, mengelola, dan menganalisis data geografis atau spasial guna menyediakan data kependudukan di Kampung Pinebentengang. Data spasial ini memberikan informasi komprehensif mengenai distribusi bantuan program pemerintah, ketersediaan sumber air bersih, kondisi jaringan listrik, infrastruktur umum, batas lindongan, dan lokasi pemukiman. Dengan menggunakan perangkat lunak open source Quantum GIS (QGIS), penelitian ini menghasilkan satu peta berbasis Web-GIS dan empat peta digital: peta persebaran penduduk, peta penerima bantuan pemerintah, peta pengguna sumber air bersih, dan peta pengguna jaringan listrik. QGIS digunakan untuk menganalisis, mengelompokkan, dan memvisualisasikan data ke dalam bentuk peta cetak dan Web-GIS. Hasil penelitian ini diharapkan dapat memberikan manfaat signifikan bagi masyarakat Kampung Pinebentengang dalam perencanaan dan pengelolaan sumber daya serta pembangunan infrastruktur yang lebih efisien dan tepat sasaran. Selain itu, data spasial ini juga dapat mendukung pengambilan keputusan yang lebih baik oleh pemerintah dan pihak terkait dalam distribusi bantuan serta pembangunan fasilitas umum yang lebih efektif dan berkelanjutan.',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Alfira Anggela Tamusa',
        NIM: '2105006',
        Angkatan: '2021',
        judul: 'Proyeksi Data Penduduk Diwilayah Tahuna Dengan Metode Least Square',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Alisa Papendang',
        NIM: '2105007',
        Angkatan: '2021',
        judul: 'Website Pengolahan Data Jemaat GMIST Ararat Nahepese',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Anggraini Makianggung',
        NIM: '2105009',
        Angkatan: '2021',
        judul: 'Sistem Informasi Penerbitan Rekomendasi Izin Usaha Ternak Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Aprilia Angelika Dalapan',
        NIM: '2105010',
        Angkatan: '2021',
        judul: 'Perancangan Web Portal Kampung Tawoali',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Ariel Ludvic Makakombo',
        NIM: '2105013',
        Angkatan: '2021',
        judul: 'Web GIS Pemberdayaan Tanah Masyarakat di Daerah Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Arum Sari Anwar',
        NIM: '2105015',
        Angkatan: '2021',
        judul: 'Sistem Informasi Penanganan Kapal Asing Ilegal di Stasuin PSDKP Tahuna Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Arya Marselino Putra Adrian',
        NIM: '2105016',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pelayanan Dive Guide dan Paket Dive Trip',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Astika Theresa Jangkobus',
        NIM: '2105017',
        Angkatan: '2021',
        judul: 'Sistem Informasi Kenaikan Pangkat dan Kenaikan Gaji Berkala Berbasis Web Dinas Pertanian Daerah Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Calvin Datundelang',
        NIM: '2105018',
        Angkatan: '2021',
        judul: 'Website Pusat Data dan Informasi Pos SAR Tahuna',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Christin Valentine Kaburuang',
        NIM: '2105020',
        Angkatan: '2021',
        judul: 'Design Thinking Pengembangan UI/UX Website Sangihe Learning Center',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Cicilia Hontong',
        NIM: '2105021',
        Angkatan: '2021',
        judul: 'Sistem Informasi Profil POLSEK Tahuna Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Dejoses Mesias Pianaung',
        NIM: '2105025',
        Angkatan: '2021',
        judul: 'Sistem Informasi Data Penjualan Spare Part dan Servis Motor Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Desy Natalia Singa',
        NIM: '2105026',
        Angkatan: '2021',
        judul: 'Sistem Informasi Profil Tanaman Pangan dan Hortikultura Dinas Pertanian Daerah Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Devid Cordias Diamanis',
        NIM: '2105027',
        Angkatan: '2021',
        judul: 'Redistribusi Tanah Berbasis Mobile',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Dian Nastasia Bogar',
        NIM: '2105028',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pelayanan Posyandu Kampung Tawoali Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Eferson Saselah',
        NIM: '2105030',
        Angkatan: '2021',
        judul: 'Sistem Informasi Backend Pengelola Data Redistribusi Tanah Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Enginia Natalia Mandiangan',
        NIM: '2105032',
        Angkatan: '2021',
        judul: 'Sistem Informasi Indeks Kepuasan Masyarakat Pengguna Layanan Publik di Stasuin PSDKP Tahuna Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Febry Angeline Sirape',
        NIM: '2105033',
        Angkatan: '2021',
        judul: 'Sistem Informasi Survei Kepuasan Masyarakat Terhadap Pelayanan Publik di Dinas Pekerjaan Umum dan Penataan Ruang Daerah Kabupatan Kepulauan Sangihe Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Febryan Luther Barahama',
        NIM: '2105034',
        Angkatan: '2021',
        judul: 'Penerapan React Javascript pada Front End Website Sangihe Learning Center',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Fihqry Syawal Y. Achmad',
        NIM: '2105035',
        Angkatan: '2021',
        judul: 'Sistem Infromasi Manajemen Program Kerja Tim Penggerak PKK Kampung Petta Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Firma Lasar Tasin',
        NIM: '2105036',
        Angkatan: '2021',
        judul: 'Rancang Bangun Sistem Produksi Kerajinan Bambu Batik Usaha Mikro, Kecil dan Menengah Kampuns Bowongkulu 1 Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Fitriani Hamenda',
        NIM: '2105037',
        Angkatan: '2021',
        judul: 'Sistem Infromasi Pengarsipan Dokumen Pembuatan Kapal Nelayan Berbasis Website',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Friska Gabriella Mundewoba',
        NIM: '2105039',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pendataan Lowongan Kerja di Kantor Dinas Tenaga Kerja Daerah Kabupaten Kepulauan Sangihe Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Friska Teresya Makaluase',
        NIM: '2105040',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pelayanan Pengaduan Tenaga Kerja di Kantor Dinas Tenaga Kerja Daerah Kabupaten Kepulauan Sangihe Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Gisca Gian Mehengkelambung',
        NIM: '2105042',
        Angkatan: '2021',
        judul: 'Sistem Informasi Promosi Produk Usaha Mikro Kecil Menengah Utaurano Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Gledis Lauransia Lohige',
        NIM: '2105043',
        Angkatan: '2021',
        judul: 'Desain UI/UX Website Pusat Data dan Informasi POS SAR Tahuna pada Segimen End User',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Grece Norani Tamanung',
        NIM: '2105044',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pengarsipan Surat Masuk dan Keluar pada Kampung Utaurano Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Haswanti Daeng Salasa',
        NIM: '2105045',
        Angkatan: '2021',
        judul: 'Sistem Infromasi Rekomendasi SKCK di POLSEK Tahuna Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Jeane Chatrina Bulele',
        NIM: '2105048',
        Angkatan: '2021',
        judul: 'Sistem Informasi Penjualan Hasil Karya Warga Binaan Pemasyarakatan Segmen Admin',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Jerianto Yohanes Mandalika',
        NIM: '2105049',
        Angkatan: '2021',
        judul: 'Sistem Informasi Manajemen Data Inventaris dan Infrastruktur Pemerintah Kawasan Perbatasan pada Badan Pengelola Perbatasan Daerah Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Joshua Ebenhaezer Manossoh',
        NIM: '2105051',
        Angkatan: '2021',
        judul: 'Penerapan Framework Laravel pada Back End Website LKP Sangihe Learning Center',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Julio Jilberd Mododahi',
        NIM: '2105053',
        Angkatan: '2021',
        judul: 'Penerapan Model Overlay Layer Untuk Visualisasi Sebaran Mamalia Pada Kawasan Hutan Lindung Sahendaruman II',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Julio Rikcofandi Lantemona',
        NIM: '2105054',
        Angkatan: '2021',
        judul: 'Web GIS Spot Dive Kepulauan Sangihe dengan Forecasting API',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Kristia Mirnawati Tumpias',
        NIM: '2105057',
        Angkatan: '2021',
        judul: 'Sistem Informasi Profil Sekolah Luar Biasa di Kabupaten Kepulauan Sangihe Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Leondardo Rio Patras',
        NIM: '2105058',
        Angkatan: '2021',
        judul: 'Sistem Informasi Front End Pengelolaan Data Redistribusi Tanah Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Lia Christy Masoara',
        NIM: '2105059',
        Angkatan: '2021',
        judul: 'Sistem Informasi Persediaan Barang di Gudang Perusahaan Daerah Air Minum Tahuna Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Maria Andriani Nani',
        NIM: '2105061',
        Angkatan: '2021',
        judul: 'Web GIS Pengolahan Data Pergerakan Kapal Ilegal di Wilayah Perairan Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Maysi Sisilia Belawati Israel',
        NIM: '2105062',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pemantauan dan Perlindungan Spesies Ikan Terancam Punah di Perairan Tahuna',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Mayske Angelica Takasihaeng',
        NIM: '2105063',
        Angkatan: '2021',
        judul: 'Sistem Informasi Kondisi Pantai Berbasis Web GIS',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Marlin Angelita Lukas',
        NIM: '2105064',
        Angkatan: '2021',
        judul: 'Sistem Informasi Akademik SMK Negeri 1 Tabukan Tengah Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Novlin Viyolces Ingrita Kumalaka',
        NIM: '2105066',
        Angkatan: '2021',
        judul: 'Sistem Informasi Surat Perintah Perjalanan Dinas Berbasis Website di Kampung Utaurano',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Nur Afni Tulusang',
        NIM: '2105067',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pengaduan Gangguan PDAM Tahuna Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Nurvita Sene',
        NIM: '2105068',
        Angkatan: '2021',
        judul: 'Proyeksi Tenaga Kerja dengan Metode Geometrik dan Aritmatika di Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Rahmawati Ussu',
        NIM: '2105071',
        Angkatan: '2021',
        judul: 'Rancang Bangun Sistem Informasi Pengolahan Data Aset Kampung Petta Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Remona Amanda Patricia Kakunsi',
        NIM: '2105072',
        Angkatan: '2021',
        judul: 'Sistem Infromasi Sanitasi Air Limbah Berbasis Web di Dinas Pekerjaan Umum dan Penataan Ruang Daerah Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Reinalto Derek',
        NIM: '2105073',
        Angkatan: '2021',
        judul: 'Implementasi Agile Scrum dalam Pengembangan Learning Management System di Infinite Learning',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Reni Mehare',
        NIM: '2105074',
        Angkatan: '2021',
        judul: 'Perancangan Website Profil SMK Negeri 1 Tabukan Tengah',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Richi Natanael Lawere',
        NIM: '2105075',
        Angkatan: '2021',
        judul: 'Desain Perencangan Survei Keanekaragaman Spesies Hutan Lindung Gunung Sahendaruman II Menggunakan Model Line Transec dan Point Count Berbasis On Screen Mobile Maps',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Rivandi Lambari',
        NIM: '2105076',
        Angkatan: '2021',
        judul: 'Digitalisasi Warkah Berbasis Web pada Kantor Pertanahan Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Ruth Lady Trully Mambrasar',
        NIM: '2105077',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pejualan Hasil Karya Warga Binaan Pemasyarakatan Segmen Pelanggan',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Sadillah Madinah Muji Astutik',
        NIM: '2105078',
        Angkatan: '2021',
        judul: 'Sistem Pendaftaran Kunjungan di Lembaga Pemasyarakatan Kelas IIB Tahuna Berbasis Website',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Sarmila Salilo',
        NIM: '2105079',
        Angkatan: '2021',
        judul: 'Sistem Informasi Zona Nilai Tanah',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Sastia Asti Pido',
        NIM: '2105081',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pendataan Aktivitas Perkapalan Berbasis Website',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Seventiny Novrianingsih Lantemona',
        NIM: '2105082',
        Angkatan: '2021',
        judul: 'Web GIS Monitoring Sebaran Penerima Bantuan Sosial Kampung Tawoali',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Sifky Alexanro Makaluwu',
        NIM: '2105083',
        Angkatan: '2021',
        judul: 'Implementasi ArcGIS untuk Tata Guna Lahan Partisipatif Masyarakat Kampung Menggawa 2',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Silvia Regina Makarui',
        NIM: '2105084',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pengelolaan Data Panti Asuhan Berbasis Web di Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Siti Srifanti Lesawengen',
        NIM: '2105085',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pengelolaan Administrasi Usaha Mikro Kecil Menengah (UMKM) Pandai Besi Kampng Petta Selatan Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Vivin Evie Mema',
        NIM: '2105090',
        Angkatan: '2021',
        judul: 'Sistem Verifikasi Data Kapal Nelayan Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Vivin Lelly Sahede',
        NIM: '2105091',
        Angkatan: '2021',
        judul: 'Sistem Informasi Surat Perintah Perjalanan Dinas Berbasis Web Menggunakan Notifikasi Telegram',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Yusuf Gabriel Wuaten',
        NIM: '2105092',
        Angkatan: '2021',
        judul: 'Sistem Informasi Manajemen Penerimaan Bantuan Kampung Petta Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Chelinda Runtuwene',
        NIM: '2105095',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pembangunan Air Bersih di Dinas PUPRD',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Pangeran Jouce Djarang',
        NIM: '2105096',
        Angkatan: '2021',
        judul: 'Identifikasi Kelayakan Pertimbangan Teknis Pertahanan Pembangunan Tower Bakti KOMINFO Menggunakan Sistem Informasi Geografis Berbasis Aturan',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Judha Rachmat Surudani',
        NIM: '2105105',
        Angkatan: '2021',
        judul: 'Sistem Informasi Pengurusan Rekomendasi Izin Jalan pada Dinas Perhubungan Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
]

export {DataMahasiswa2021}

const DataMahasiswa2022 = [
    {
        Photo: amel,
        Nama: 'Amels Wisye Margareth Sasauw',
        NIM: '2205002',
        Angkatan: '2022',
        judul: 'Sistem Informasi Inventarisasi Aset Daerah Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: alicia,
        Nama: 'Alicia Aurelia Hebingadil',
        NIM: '2205003',
        Alias: 'cia',
        Angkatan: '2022',
        judul: 'Pengembangan Web GIS Sistem Pemantauan Hasil Perikanan',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Junior Kefas Mahino',
        NIM: '2205004',
        Angkatan: '2022',
        judul: 'Sistem Informasi Sebaran Anak Stunting di Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Mersita Trisce Letunggamu',
        NIM: '2205006',
        Angkatan: '2022',
        judul: 'Sistem Informasi Akreditasi Sekolah di Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: reisky,
        Nama: 'Reisky Mendalora Sahentumuwo',
        Alias: 'yono',
        NIM: '2205009',
        Angkatan: '2022',
        judul: 'Web GIS Sebaran Lahan Pertanian di Tahuna Barat',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: cici,
        Nama: 'Regina Glorita Makaluase',
        Alias: 'cici',
        NIM: '2205010',
        Angkatan: '2022',
        judul: 'Sistem Informasi Penyediaan Air Moil Tangki Berbasis Website',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: fadhilla,
        Nama: 'Fadhilla Wahyuni Soleman',
        Alias: 'dila',
        NIM: '2205011',
        Angkatan: '2022',
        judul: 'Analisis Sistem Monitoring Infrastruktur pada Program Pembangunan dan Pemberdayaan Masyarakat dan Desa',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: januard,
        Nama: 'Januard Reynaldi Alexandro Andaria',
        Alias: 'didi',
        NIM: '2205013',
        Angkatan: '2022',
        judul: 'Sistem Informasi Event dan Reservasi Makanan di KOPITIAM Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: valen,
        Nama: 'Greyfer Valentino Papendang Legrants',
        NIM: '2205014',
        Angkatan: '2022',
        judul: 'Sistem Informasi Monitoring Harga Sembako Berbasis Web pada Dinas Perindustrian dan Perdagangan Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: mega,
        Nama: 'Mega Olivia Busia Pinta',
        NIM: '2205015',
        Angkatan: '2022',
        judul: 'Sistem Infromasi Kesehatan Posyandu Anak Balita Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Akhsa Angel Tumbale',
        Alias: 'emot batu, emotbatu',
        NIM: '2205016',
        Angkatan: '2022',
        judul: 'Membuat Surat Keterangan Kehilangan Barang Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: christy,
        Nama: 'Christy Stevani Tamusa',
        Alias: 'tilu',
        NIM: '2205017',
        Angkatan: '2022',
        judul: 'Sistem Infromasi Kesehatan Gizi Remaja Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: aisyah,
        Nama: 'Sitti Aisyah Mahare',
        NIM: '2205019',
        Angkatan: '2022',
        judul: 'Pengembangan Sistem Monitoring Infrastruktur Pada Program Pembangunan dan Pemberdayaan Masyarakat',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: idax,
        Nama: 'Evandrix Mamintade',
        Alias: 'idax, nasir',
        NIM: '2205020',
        Angkatan: '2022',
        judul: 'Digitalisasi Potensi Kampung Kawio Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: achel,
        Nama: 'Firstonly Marshel Naharia',
        Alias: 'achel, acel, big',
        NIM: '2205021',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: andika,
        Nama: 'Andika Eka Koming',
        NIM: '2205023',
        Angkatan: '2022',
        judul: 'Aplikasi Pengolahan Data Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Jessica Juanita Lombontari',
        Alias: 'emot batu, emotbatu',
        NIM: '2205024',
        Angkatan: '2022',
        judul: 'Inventaris SOP pada Lembaga Pemasyarakatan Kelas III Enemawira Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: faujia,
        Nama: 'Faujia Kondoalumang',
        NIM: '2205025',
        Angkatan: '2022',
        judul: 'Sistem Informasi Layanan Pendaftaran Penyambungan Baru di PDAM Berbasis Website',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: iya,
        Nama: 'Zuwairyah Kantohe',
        Alias: 'iya',
        NIM: '2205026',
        Angkatan: '2022',
        judul: 'Sistem Informasi Pendaftaran dan Pendampingan UMKM di Loka POM Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Sheren Zyallomitha Zhakilla Makawimbang',
        Alias: 'eyen',
        NIM: '2205030',
        Angkatan: '2022',
        judul: 'Desain UI/UX Inventaris SOP pada Lembaga Pemasyarakatan Kelas III Enemawira',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: julieo,
        Nama: 'Julieo Yusuf Kagingge',
        Alias: 'jule, jules, juls, Jboyy',
        NIM: '2205031',
        Angkatan: '2022',
        judul: 'Sistem Informasi Manajemen (SIM) Data Perpustakaan',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: supriadi,
        Nama: 'Supriadinata Masihor',
        Alias: 'upi',
        NIM: '2205032',
        Angkatan: '2022',
        judul: 'Sistem Informasi Penjualan Produk UMKM Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: stifangki,
        Nama: 'Stifangki Josua Rivan Kakunsi',
        Alias: 'ungke',
        NIM: '2205033',
        judul: 'Pemanfaatan Aplikasi ArcGIS untuk Jalur Evakuasi Gunung Berapi Awu',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Muhammad Syahban Tempongbuka',
        NIM: '2205034',
        judul: 'Sistem Informasi Jalur Pipa PDAM Berbasis Web GIS',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: delon,
        Nama: 'Novaldi Delon Takalalumang',
        Alias: 'delta',
        NIM: '2205038',
        Angkatan: '2022',
        judul: 'Optimalisasi Aplikasi Berperforma Tinggi dengan Redis pada VPS Ubuntu',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: jenifer,
        Nama: 'Jenifer Sartika Lalenoh',
        NIM: '2205039',
        Angkatan: '2022',
        judul: 'Sistem Informasi Manajemen Proyek Konstruksi Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Revalin Terah Wolff',
        NIM: '2205040',
        Angkatan: '2022',
        judul: 'Sistem Informasi Layanan Masyarakat pada POLSEK Tahuna Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: stevani,
        Nama: 'Stevani Patiri',
        Alias: 'fani',
        NIM: '2205041',
        Angkatan: '2022',
        judul: 'Penggunaan Drone untuk Identifikasi Pergeseran Garis Pantai (Studi Kasus: Kecamatan Tabukan Utara)',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: geo,
        Nama: 'Geovani Marchiano Monok',
        Alias: 'gexxyn',
        NIM: '2205042',
        Angkatan: '2022',
        judul: 'Website Monitoring Aktivitas Kunjungan Kawasan Gunung Sahendarumang',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: muzamil,
        Nama: 'Muzamil Paputungan',
        Alias: 'jamil',
        NIM: '2205043',
        Angkatan: '2022',
        judul: 'Pengelolaan Data Sebaran Keragaman Hayati Hutan Lindung Sahendarumang 2 Berbasis Web Gis',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Reggi Saputra Salawangi',
        Alias: 'Zeus, eggi',
        NIM: '2205044',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Salsabillah Kaehe',
        NIM: '2205047',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Fryska Armelia Towoliu',
        Alias: 'pika',
        NIM: '2205048',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: tirsa,
        Nama: 'Tirsa Olivia Talete',
        Alias: 'dede',
        NIM: '2205049',
        Angkatan: '2022',
        judul: 'Desain UI/UX Sistem Informasi Ecent dan Reservasi Makanan di KOPITIAM Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: niken,
        Nama: 'Aniken Amasya Lendeon',
        NIM: '2205050',
        Angkatan: '2022',
        judul: 'Sistem Informasi Penilaian Kualitas Layanan Wisata Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: debora,
        Nama: 'Regina Debora Lahamendu',
        Alias: 'mogi',
        NIM: '2205051',
        Angkatan: '2022',
        judul: 'Web GIS Sebaran Lahan Pertanian di Tahuna Barat',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: marentek,
        Nama: 'Marchel Hezzel Marentek',
        Alias: 'achel, acel',
        judul: 'Penyewaan Lapangan Futsal Berbasis Web',
        NIM: '2205052',
        Angkatan: '2022',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: indriani,
        Nama: 'Indriani Gratsia Tumimbang',
        NIM: '2205054',
        Angkatan: '2022',
        judul: 'Desain UI/UX Sistem Informasi Manajemen Proyek Konstruksi',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Yohana Tompo',
        NIM: '2205055',
        Angkatan: '2022',
        judul: 'Rancang Bangun Sistem Informasi Promosi Destinasi Wisata pada Kabupaten Kepulauan Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: gabriella,
        Nama: 'Gabriella Kristania Citra Kakomole',
        NIM: '2205057',
        Angkatan: '2022',
        judul: 'Desain UI/UX Pendaftaran dan Pendampingan UMKM di Loka POM Sangihe',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: billy,
        Nama: 'Billy Amstrong Tempolenehe',
        NIM: '2205059',
        Angkatan: '2022',
        judul: 'Sistem Informasi Statistik Usaha Mikro Kecil Menengah Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Tasya Lawitang',
        Alias: 'aca',
        NIM: '2205060',
        Angkatan: '2022',
        judul: 'Web GIS Laporan Operasi SAR',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Vanessa Tesalonika Dhea Bundel',
        NIM: '2205061',
        Alias: 'dea',
        Angkatan: '2022',
        judul: 'Rekomendasi Usaha Pariwisata Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: farrel,
        Nama: 'Farrel Patrick Kaburuang',
        NIM: '2205062',
        Angkatan: '2022',
        judul: 'Sistem Informasi Profil Dinas Sosial Daerah Kabupaten Kepulauan Sangihe Berbasis Web',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: 'https://via.placeholder.com/150',
        Nama: 'Sela Ester Laodini',
        Alias: 'selbe',
        NIM: '2205063',
        Angkatan: '2022',
        judul: 'Pengembangan Sistem Pelaporan Orang Hilang Berbasis Mobile',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: leo,
        Nama: 'Leo Richardo Alelo',
        Alias: 'cipay, cipai',
        NIM: '2205064',
        Angkatan: '2022',
        judul: 'Pengembangan Backend Website Attendance Management System',
        lampiran: 'https://via.placeholder.com/150',
        lampiran1: 'https://via.placeholder.com/150',
        lampiran2: 'https://via.placeholder.com/150',
    },
    {
        Photo: sean,
        Nama: 'Sean Ishak Adare',
        Alias: 'Irene002, Astaroth',
        NIM: '2205066',
        Angkatan: '2022',
        judul: 'Pengembangan Frontend Website Attendance Management System Berbasis ReactJS & TailwindCSS',
        abstrak: 'Attendance Management System (AMS) merupakan sebuah aplikasi berbasis web yang dirancang untuk mempermudah pengelolaan data kehadiran secara efisien dan terintegrasi. Sistem ini bertujuan untuk menggantikan metode manual yang rentan terhadap kesalahan pencatatan dan membutuhkan waktu lama dengan solusi digital yang lebih akurat dan mudah digunakan. AMS memungkinkan pengguna, baik administrator maupun pengguna akhir, untuk mencatat, memantau, dan mengelola kehadiran secara real - time melalui antarmuka yang intuitif. Pengembangan AMS menggunakan teknologi ReactJS, Vite, TailwindCSS untuk antarmuka pengguna, serta ExpressJS pada sisi backend, memastikan performa yang cepat dan responsif. Sistem ini mendukung berbagai fitur seperti pencatatan kehadiran berbasis waktu nyata, pengelolaan data pengguna, laporan kehadiran yang dapat diunduh, dan pengaturan izin pengguna. Dengan implementasi AMS, institusi pendidikan, perusahaan, maupun organisasi lainnya dapat meningkatkan efisiensi pengelolaan kehadiran, mengurangi risiko kesalahan data, serta mempermudah analisis kehadiran melalui laporan yang komprehensif. Sistem ini memberikan solusi yang relevan untuk kebutuhan manajemen kehadiran modern.',
        journalLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        lampiran: seanLampiran1,
        lampiran1: seanLampiran2,
        lampiran2: 'https://via.placeholder.com/150',
    },
]

export default DataMahasiswa2022